// Type declarations for contract artifact JSON files.
// These files are generated by `nargo compile` + `bb aztec_process`.
// Copy compiled artifacts here after building contracts.

declare module '*.json' {
  const value: Record<string, any>;
  export default value;
}
