import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
import { nodePolyfills } from 'vite-plugin-node-polyfills';

/**
 * Vite plugin that serves .wasm files from node_modules with correct MIME type.
 *
 * Problem: Vite pre-bundles @aztec/wallets/embedded, which inlines code from
 * @aztec/noir-acvm_js and @aztec/noir-noirc_abi. Those use
 * `new URL('xxx.wasm', import.meta.url)` to load WASM. After bundling,
 * import.meta.url points to the Vite deps directory (.vite/deps/), not the
 * original package location, so the .wasm fetch 404s and Vite returns index.html.
 *
 * Solution: At server start, scan node_modules/@aztec for all .wasm files and
 * build a filename→path lookup. Then intercept any .wasm request and serve the
 * real file regardless of what directory path the browser requests.
 */
function serveWasm(): Plugin {
  const wasmMap = new Map<string, string>();

  function scanForWasm(dir: string): void {
    let entries: fs.Dirent[];
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // Skip nodejs variants — prefer web for browser context
        if (entry.name === 'nodejs') continue;
        scanForWasm(full);
      } else if (entry.name.endsWith('.wasm') && !wasmMap.has(entry.name)) {
        wasmMap.set(entry.name, full);
      }
    }
  }

  return {
    name: 'serve-wasm',
    configureServer(server) {
      scanForWasm(path.join(process.cwd(), 'node_modules', '@aztec'));

      server.middlewares.use((req, res, next) => {
        if (!req.url || !req.url.includes('.wasm')) return next();

        const filename = path.basename(req.url.split('?')[0]);
        const filePath = wasmMap.get(filename);
        if (filePath) {
          res.setHeader('Content-Type', 'application/wasm');
          res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
          res.setHeader('Cross-Origin-Embedder-Policy', 'credentialless');
          fs.createReadStream(filePath).pipe(res);
          return;
        }
        next();
      });
    },
  };
}

export default defineConfig({
  define: {
    'process.env': {},
  },
  plugins: [
    serveWasm(),
    react(),
    nodePolyfills({
      globals: { Buffer: true, process: true },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  optimizeDeps: {
    // Exclude Aztec packages that use `import.meta.url` at runtime:
    // - bb.js: Workers via `new Worker(new URL('./worker.js', import.meta.url))`
    // - wallets: transitively depends on bb-prover → bb.js; pre-bundling
    //   wallets breaks the module context chain that bb.js Workers need.
    // - noir-acvm_js / noir-noirc_abi: WASM via `new URL('*.wasm', import.meta.url)`
    //
    // Force-include CJS deps of excluded packages so Vite pre-bundles them
    // separately. Excluded packages' imports get rewritten to the pre-bundled
    // versions, giving us proper CJS→ESM conversion without breaking Workers.
    exclude: [
      '@aztec/bb.js',
      '@aztec/wallets',
      '@aztec/noir-acvm_js',
      '@aztec/noir-noirc_abi',
      // Also exclude @aztec packages imported directly by app code.
      // Without this, the app gets pre-bundled copies of Fr/AztecAddress/etc
      // while excluded @aztec/wallets gets node_modules copies — different
      // class instances that fail instanceof/BaseField ctor checks.
      '@aztec/foundation',
      '@aztec/aztec.js',
      '@aztec/stdlib',
    ],
    // CJS deps of excluded @aztec packages that need pre-bundling for
    // CJS→ESM conversion. Without this, Vite serves them raw from
    // node_modules and named imports fail.
    // Generated by scanning browser entry points of excluded packages.
    include: [
      'pino',
      'sha3',
      'hash.js',
      'detect-node',
      'json-stringify-deterministic',
      'lodash.chunk',
      'lodash.isequal',
      'lodash.merge',
      'lodash.pickby',
      'lodash.times',
    ],
  },
  server: {
    port: 5173,
    headers: {
      // Required for SharedArrayBuffer (bb.js threaded WASM).
      // bb.js v4 single-threaded WASM is broken (crashes with proc_exit).
      // These headers enable threaded WASM which works correctly.
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'credentialless',
    },
    proxy: {
      '/api': 'http://localhost:3001',
    },
  },
  worker: {
    format: 'es',
  },
});
