
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import CloakRegistryContractArtifactJson from '../../target/cloak_registry-CloakRegistry.json' with { type: 'json' };
export const CloakRegistryContractArtifact = loadContractArtifact(CloakRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract CloakRegistry;
 */
export class CloakRegistryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, CloakRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): CloakRegistryContract {
    return Contract.at(address, CloakRegistryContract.artifact, wallet) as CloakRegistryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<CloakRegistryContract>(PublicKeys.default(), wallet, CloakRegistryContractArtifact, (instance, wallet) => CloakRegistryContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<CloakRegistryContract>(publicKeys, wallet, CloakRegistryContractArtifact, (instance, wallet) => CloakRegistryContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CloakRegistryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<CloakRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<CloakRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      CloakRegistryContractArtifact,
      (instance, wallet) => CloakRegistryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CloakRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(CloakRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'name_to_cloak' | 'cloak_to_name' | 'cloak_count'> {
      return {
        name_to_cloak: {
      slot: new Fr(1n),
    },
cloak_to_name: {
      slot: new Fr(2n),
    },
cloak_count: {
      slot: new Fr(3n),
    }
      } as ContractStorageLayout<'name_to_cloak' | 'cloak_to_name' | 'cloak_count'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_cloak_by_name(name: string) */
    get_cloak_by_name: ((name: string) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_cloak_count() */
    get_cloak_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_name_hash_by_cloak(cloak_address: struct) */
    get_name_hash_by_cloak: ((cloak_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_name_available(name: string) */
    is_name_available: ((name: string) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_name_hash_taken(name_hash: field) */
    is_name_hash_taken: ((name_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register(name: string, cloak_address: struct) */
    register: ((name: string, cloak_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
