
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import governor_bravo_cloak.GovernorBravoCloakContractArtifactJson from '../../target/governor_bravo-governor_bravo_cloak.json' with { type: 'json' };
export const governor_bravo_cloak.GovernorBravoCloakContractArtifact = loadContractArtifact(governor_bravo_cloak.GovernorBravoCloakContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract governor_bravo_cloak.GovernorBravoCloak;
 */
export class governor_bravo_cloak.GovernorBravoCloakContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, governor_bravo_cloak.GovernorBravoCloakContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): governor_bravo_cloak.GovernorBravoCloakContract {
    return Contract.at(address, governor_bravo_cloak.GovernorBravoCloakContract.artifact, wallet) as governor_bravo_cloak.GovernorBravoCloakContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, name: string, governance_token: AztecAddressLike, voting_delay: (bigint | number), voting_period: (bigint | number), proposal_threshold: (bigint | number), quorum_numerator: (bigint | number), quorum_denominator: (bigint | number), late_quorum_extension: (bigint | number), timelock_delay: (bigint | number), proposal_guardian: AztecAddressLike, membership_mode: (bigint | number), token_gate_address: AztecAddressLike, erc20_token_address_hash: FieldLike, erc20_min_balance: (bigint | number), cloak_mode: (bigint | number), council_members: AztecAddressLike[], council_count: (bigint | number), council_threshold: (bigint | number), emergency_threshold: (bigint | number)) {
    return new DeployMethod<governor_bravo_cloak.GovernorBravoCloakContract>(PublicKeys.default(), wallet, governor_bravo_cloak.GovernorBravoCloakContractArtifact, (instance, wallet) => governor_bravo_cloak.GovernorBravoCloakContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, name: string, governance_token: AztecAddressLike, voting_delay: (bigint | number), voting_period: (bigint | number), proposal_threshold: (bigint | number), quorum_numerator: (bigint | number), quorum_denominator: (bigint | number), late_quorum_extension: (bigint | number), timelock_delay: (bigint | number), proposal_guardian: AztecAddressLike, membership_mode: (bigint | number), token_gate_address: AztecAddressLike, erc20_token_address_hash: FieldLike, erc20_min_balance: (bigint | number), cloak_mode: (bigint | number), council_members: AztecAddressLike[], council_count: (bigint | number), council_threshold: (bigint | number), emergency_threshold: (bigint | number)) {
    return new DeployMethod<governor_bravo_cloak.GovernorBravoCloakContract>(publicKeys, wallet, governor_bravo_cloak.GovernorBravoCloakContractArtifact, (instance, wallet) => governor_bravo_cloak.GovernorBravoCloakContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof governor_bravo_cloak.GovernorBravoCloakContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<governor_bravo_cloak.GovernorBravoCloakContract['methods'][M]>
  ) {
    return new DeployMethod<governor_bravo_cloak.GovernorBravoCloakContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      governor_bravo_cloak.GovernorBravoCloakContractArtifact,
      (instance, wallet) => governor_bravo_cloak.GovernorBravoCloakContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return governor_bravo_cloak.GovernorBravoCloakContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(governor_bravo_cloak.GovernorBravoCloakContractArtifactJson as NoirCompiledContract);
  }
  

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cancel(proposal_id: field) */
    cancel: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cast_fractional_vote(proposal_id: field, for_weight: integer, against_weight: integer, abstain_weight: integer) */
    cast_fractional_vote: ((proposal_id: FieldLike, for_weight: (bigint | number), against_weight: (bigint | number), abstain_weight: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cast_vote(proposal_id: field, support: integer) */
    cast_vote: ((proposal_id: FieldLike, support: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cast_vote_with_reason(proposal_id: field, support: integer, _reason_hash: field) */
    cast_vote_with_reason: ((proposal_id: FieldLike, support: (bigint | number), _reason_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(name: string, governance_token: struct, voting_delay: integer, voting_period: integer, proposal_threshold: integer, quorum_numerator: integer, quorum_denominator: integer, late_quorum_extension: integer, timelock_delay: integer, proposal_guardian: struct, membership_mode: integer, token_gate_address: struct, erc20_token_address_hash: field, erc20_min_balance: integer, cloak_mode: integer, council_members: array, council_count: integer, council_threshold: integer, emergency_threshold: integer) */
    constructor: ((name: string, governance_token: AztecAddressLike, voting_delay: (bigint | number), voting_period: (bigint | number), proposal_threshold: (bigint | number), quorum_numerator: (bigint | number), quorum_denominator: (bigint | number), late_quorum_extension: (bigint | number), timelock_delay: (bigint | number), proposal_guardian: AztecAddressLike, membership_mode: (bigint | number), token_gate_address: AztecAddressLike, erc20_token_address_hash: FieldLike, erc20_min_balance: (bigint | number), cloak_mode: (bigint | number), council_members: AztecAddressLike[], council_count: (bigint | number), council_threshold: (bigint | number), emergency_threshold: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** council_approve(proposal_id: field) */
    council_approve: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** delegate(delegatee: struct) */
    delegate: ((delegatee: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** emergency_cancel(proposal_id: field) */
    emergency_cancel: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** emergency_execute(proposal_id: field) */
    emergency_execute: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** execute(proposal_id: field) */
    execute: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_cloak_mode() */
    get_cloak_mode: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_council_approval_count(proposal_id: field) */
    get_council_approval_count: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_council_count() */
    get_council_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_council_member(index: integer) */
    get_council_member: ((index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_council_threshold() */
    get_council_threshold: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_delegate(account: struct) */
    get_delegate: ((account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_effective_votes(account: struct) */
    get_effective_votes: ((account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_emergency_threshold() */
    get_emergency_threshold: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_erc20_config() */
    get_erc20_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_governance_token() */
    get_governance_token: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_late_quorum_extension() */
    get_late_quorum_extension: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_membership_mode() */
    get_membership_mode: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_name() */
    get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal(proposal_id: field) */
    get_proposal: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_count() */
    get_proposal_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_guardian() */
    get_proposal_guardian: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_threshold() */
    get_proposal_threshold: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quorum_denominator() */
    get_quorum_denominator: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quorum_numerator() */
    get_quorum_numerator: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_timelock_delay() */
    get_timelock_delay: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_token_gate_address() */
    get_token_gate_address: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_voting_power() */
    get_total_voting_power: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_votes(account: struct) */
    get_votes: ((account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_voting_delay() */
    get_voting_delay: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_voting_period() */
    get_voting_period: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** hash_proposal(actions_hash: field, description_hash: field) */
    hash_proposal: ((actions_hash: FieldLike, description_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_council_member(addr: struct) */
    is_council_member: ((addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_with_erc20_proof(verified_balance: integer, proof_nullifier: field) */
    join_with_erc20_proof: ((verified_balance: (bigint | number), proof_nullifier: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_with_token_proof(balance_commitment: field) */
    join_with_token_proof: ((balance_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** proposal_deadline(proposal_id: field) */
    proposal_deadline: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** proposal_eta(proposal_id: field) */
    proposal_eta: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** proposal_proposer(proposal_id: field) */
    proposal_proposer: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** proposal_snapshot(proposal_id: field) */
    proposal_snapshot: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** proposal_state(proposal_id: field) */
    proposal_state: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** proposal_votes(proposal_id: field) */
    proposal_votes: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** propose(actions_hash: field, description_hash: field, target_count: integer, proposal_type: integer) */
    propose: ((actions_hash: FieldLike, description_hash: FieldLike, target_count: (bigint | number), proposal_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** queue(proposal_id: field) */
    queue: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** quorum(block_number: integer) */
    quorum: ((block_number: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
