
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import molt_cloak.MoltCloakContractArtifactJson from '../../target/molt_cloak-molt_cloak.json' with { type: 'json' };
export const molt_cloak.MoltCloakContractArtifact = loadContractArtifact(molt_cloak.MoltCloakContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract molt_cloak.MoltCloak;
 */
export class molt_cloak.MoltCloakContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, molt_cloak.MoltCloakContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): molt_cloak.MoltCloakContract {
    return Contract.at(address, molt_cloak.MoltCloakContract.artifact, wallet) as molt_cloak.MoltCloakContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, name: string, admin: AztecAddressLike, privacy_preset: (bigint | number), discussion_public: boolean, post_cooldown_blocks: (bigint | number), comment_cooldown_blocks: (bigint | number), daily_comment_limit: (bigint | number), voting_period_blocks: (bigint | number)) {
    return new DeployMethod<molt_cloak.MoltCloakContract>(PublicKeys.default(), wallet, molt_cloak.MoltCloakContractArtifact, (instance, wallet) => molt_cloak.MoltCloakContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, name: string, admin: AztecAddressLike, privacy_preset: (bigint | number), discussion_public: boolean, post_cooldown_blocks: (bigint | number), comment_cooldown_blocks: (bigint | number), daily_comment_limit: (bigint | number), voting_period_blocks: (bigint | number)) {
    return new DeployMethod<molt_cloak.MoltCloakContract>(publicKeys, wallet, molt_cloak.MoltCloakContractArtifact, (instance, wallet) => molt_cloak.MoltCloakContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof molt_cloak.MoltCloakContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<molt_cloak.MoltCloakContract['methods'][M]>
  ) {
    return new DeployMethod<molt_cloak.MoltCloakContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      molt_cloak.MoltCloakContractArtifact,
      (instance, wallet) => molt_cloak.MoltCloakContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return molt_cloak.MoltCloakContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(molt_cloak.MoltCloakContractArtifactJson as NoirCompiledContract);
  }
  

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cast_vote(proposal_id: integer, support: boolean) */
    cast_vote: ((proposal_id: (bigint | number), support: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** complete_verification(nonce_hash: field, twitter_hash: field) */
    complete_verification: ((nonce_hash: FieldLike, twitter_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(name: string, admin: struct, privacy_preset: integer, discussion_public: boolean, post_cooldown_blocks: integer, comment_cooldown_blocks: integer, daily_comment_limit: integer, voting_period_blocks: integer) */
    constructor: ((name: string, admin: AztecAddressLike, privacy_preset: (bigint | number), discussion_public: boolean, post_cooldown_blocks: (bigint | number), comment_cooldown_blocks: (bigint | number), daily_comment_limit: (bigint | number), voting_period_blocks: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_comment(content_hash: field, post_id: integer, parent_comment_id: integer) */
    create_comment: ((content_hash: FieldLike, post_id: (bigint | number), parent_comment_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_post(content_hash: field, submolt_id: integer) */
    create_post: ((content_hash: FieldLike, submolt_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_proposal(content_hash: field, proposal_type: integer) */
    create_proposal: ((content_hash: FieldLike, proposal_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_submolt(name_hash: field) */
    create_submolt: ((name_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** delete_post(post_id: integer) */
    delete_post: ((post_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** downvote_comment(comment_id: integer) */
    downvote_comment: ((comment_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** downvote_post(post_id: integer) */
    downvote_post: ((post_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** execute_proposal(proposal_id: integer) */
    execute_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_agent_count() */
    get_agent_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_claim_agent(nonce_hash: field) */
    get_claim_agent: ((nonce_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_author(id: integer) */
    get_comment_author: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_content_hash(id: integer) */
    get_comment_content_hash: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_count() */
    get_comment_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_created_at(id: integer) */
    get_comment_created_at: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_parent_id(id: integer) */
    get_comment_parent_id: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_post_id(id: integer) */
    get_comment_post_id: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_comment_votes(id: integer) */
    get_comment_votes: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_discussion_public() */
    get_discussion_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_name() */
    get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_post_author(id: integer) */
    get_post_author: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_post_content_hash(id: integer) */
    get_post_content_hash: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_post_count() */
    get_post_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_post_created_at(id: integer) */
    get_post_created_at: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_post_submolt(id: integer) */
    get_post_submolt: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_post_votes(id: integer) */
    get_post_votes: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_author(id: integer) */
    get_proposal_author: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_content_hash(id: integer) */
    get_proposal_content_hash: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_count() */
    get_proposal_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_end_block(id: integer) */
    get_proposal_end_block: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_status(id: integer) */
    get_proposal_status: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_type(id: integer) */
    get_proposal_type: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_votes(id: integer) */
    get_proposal_votes: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_rate_limits() */
    get_rate_limits: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_submolt(id: integer) */
    get_submolt: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_submolt_count() */
    get_submolt_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_voting_period_blocks() */
    get_voting_period_blocks: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_agent_verified(agent: struct) */
    is_agent_verified: ((agent: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_claim_verified(nonce_hash: field) */
    is_claim_verified: ((nonce_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_post_deleted(id: integer) */
    is_post_deleted: ((id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_claim(nonce_hash: field) */
    register_claim: ((nonce_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** upvote_comment(comment_id: integer) */
    upvote_comment: ((comment_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** upvote_post(post_id: integer) */
    upvote_post: ((post_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
