
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MultiAuthAccountContractArtifactJson from '../../target/multi_auth_account-MultiAuthAccount.json' with { type: 'json' };
export const MultiAuthAccountContractArtifact = loadContractArtifact(MultiAuthAccountContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MultiAuthAccount;
 */
export class MultiAuthAccountContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MultiAuthAccountContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MultiAuthAccountContract {
    return Contract.at(address, MultiAuthAccountContract.artifact, wallet) as MultiAuthAccountContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, key_type: (bigint | number), public_key_hash: FieldLike, label_hash: FieldLike) {
    return new DeployMethod<MultiAuthAccountContract>(PublicKeys.default(), wallet, MultiAuthAccountContractArtifact, (instance, wallet) => MultiAuthAccountContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, key_type: (bigint | number), public_key_hash: FieldLike, label_hash: FieldLike) {
    return new DeployMethod<MultiAuthAccountContract>(publicKeys, wallet, MultiAuthAccountContractArtifact, (instance, wallet) => MultiAuthAccountContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MultiAuthAccountContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MultiAuthAccountContract['methods'][M]>
  ) {
    return new DeployMethod<MultiAuthAccountContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MultiAuthAccountContractArtifact,
      (instance, wallet) => MultiAuthAccountContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MultiAuthAccountContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MultiAuthAccountContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'primary_key_hash' | 'primary_key_type' | 'key_count' | 'authorized_keys' | 'key_labels' | 'display_name_hash'> {
      return {
        primary_key_hash: {
      slot: new Fr(1n),
    },
primary_key_type: {
      slot: new Fr(3n),
    },
key_count: {
      slot: new Fr(5n),
    },
authorized_keys: {
      slot: new Fr(6n),
    },
key_labels: {
      slot: new Fr(7n),
    },
display_name_hash: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'primary_key_hash' | 'primary_key_type' | 'key_count' | 'authorized_keys' | 'key_labels' | 'display_name_hash'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(key_type: integer, public_key_hash: field, label_hash: field) */
    constructor: ((key_type: (bigint | number), public_key_hash: FieldLike, label_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_display_name_hash() */
    get_display_name_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_key_count() */
    get_key_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_key_label(key_type: integer, public_key_hash: field) */
    get_key_label: ((key_type: (bigint | number), public_key_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_primary_key_hash() */
    get_primary_key_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_primary_key_type() */
    get_primary_key_type: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_key_authorized(key_type: integer, public_key_hash: field) */
    is_key_authorized: ((key_type: (bigint | number), public_key_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
